### ISSUE TITLE
convertCardsXML no longer works

### ISSUE THREAD

**Issue by macdrum** [TheSench/SIMSpellstone#15]
Error#1:  if(imageRemappings.TryGetValue(unit.id, out string remappedPortrait))

Invalid expression term 'string'

; expected

Invalid expression term ')'

and

Error #2:  suffixMap.TryGetValue(suffix, out int fusion);

**Comment by TheSench** [comment]
Hey mac, I didn't know you were still around!  Mind adding a little more detail?  The LINQ file runs fine for me, so I don't know what issue you're getting.  What version of LINQPad/.NET are you using to run it?

**Comment by macdrum** [comment]
Sench!

I'm back about a month.  So surprised to see you still involved?

App only or are you playing?

Anyway, I have linqpad4 and am now installing linqpad 5.  I'll try again
with that.

**Comment by macdrum** [comment]
Ran with no bugs in5

**Comment by macdrum** [comment]
oops new issue:

DirectoryNotFoundException: Could not find a part of the path
'C:\Users\info\AppData\Local\Temp\Temp1_SIMSpellstone-gh-pages.zip\SIMSpellstone-gh-pages\res\skills'.

**Comment by macdrum** [comment]
I have no AppData etc directory

**Comment by TheSench** [comment]
Closed - script must be run using LINQPad 5 (.NET 4.5+).
