### ISSUE TITLE
simulator broken

### ISSUE THREAD

**Issue by jimnvox** [TheSench/SIMSpellstone#16]
Received the following message when running a simulation:

`<blockquote>JavaScript error:
 Uncaught ReferenceError: target is not defined
 on line 3031
 for http://thesench.github.io/SIMSpellstone/scripts/simulator_base.js
Browser CodeName: Mozilla
Browser Name: Netscape
Browser Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Cookies Enabled: true
Platform: Linux x86_64
User-agent header: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
SimSpellstone version: v2.0
Deck hash: gn5AAA4vmCgpQSBAicuHQOwqCom~qCIcGrCge6qCozplCQkLrCI9JBF4UPBFQTcAFYborBgjtrBAerTB
Mission ID: 5886
Battleground ID: 114,128
</blockquote>`

**Comment by TheSench** [comment]
Thanks for notifying me.  This should be fixed now.

**Comment by jimnvox** [comment]
Confirmed as fixed.  Thanks for your work on this project!
