### ISSUE TITLE
terragon peak map bge bolt issue

### ISSUE THREAD

**Issue by jimnvox** [TheSench/SIMSpellstone#17]
to replicate sim terragon peak with bolt all map bge given a value (1 will do) on any node/mission (used node 3, mission 2).

error encountered:

`<blockquote>JavaScript error:
 Uncaught TypeError: unit.isActive is not a function
 on line 262
 for https://thesench.github.io/SIMSpellstone/scripts/simulator_base.js
Browser CodeName: Mozilla
Browser Name: Netscape
Browser Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Cookies Enabled: true
Platform: Linux x86_64
User-agent header: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
SimSpellstone version: v2.0
Deck hash: gn5AAwEgrCAqrhCIduCCg0VrCIWQnCIWQnCgVZBFAZ0rBodeBFo8arCo8arCIHUrCw6FlCYsQrCo5fpC
Ordered: Yes
Mission ID: 6111
Battleground ID: 105,120
</blockquote>
`

**Comment by TheSench** [comment]
Sorry about the late response - this dropped out of my inbox.  It should be
fixed now.  Thanks for reporting!

**Comment by TheSench** [comment]
Sorry about the late response - this dropped out of my inbox.  When determining if backlash should fire, the simulator was only checking that the source of damage was _not a commander_.  It is now checking that it _is a unit_ (so BGEs don't trigger it).  Thanks for reporting!
