### ISSUE TITLE
Wing Guard Still not implementing

### ISSUE THREAD

**Issue by energiste** [TheSench/SIMSpellstone#18]
For the online and downloaded versions of the sim, the latest update (5/7/2019) appears to have corrected the issue with invigorate and radiance.  However, still getting the message in debug mode:
"Verus, the Galeheart*{7/7} (3) [7/29/0] attempts to use Wing Guard, but it is not implemented."

**Comment by TheSench** [comment]
Thanks for the notice.  It should be working now.  Looks like they changed the skill ID on me back on 4/25 and I didn't catch it.
