### ISSUE TITLE
vampirism is not healing?

### ISSUE THREAD

**Issue by jimnvox** [TheSench/SIMSpellstone#20]
See the below debug log excerpt (relevant lines bolded) for example, as cauterizing fist drains 6 health, but doesn't seem to add to it's own hp:

**Centurion Spikesteel{6/6} (0) [12/27/0] attacks Cauterizing Fist{5/5} (0) [8/14/0] for 12 damage**
Hoggernaut MK III{6/6} (1) [15/48/2] is not active yet
Life Vessel{6/6} (2) [20/46/2] is not active yet
(Vampirism: +5 Ward: -9) = 0 damage
Twistwood{6/6} (3) [16/40/3] activates vampirism, draining 0 health from Absorbing Sleetbones{5/5} (3) [10/48/4]
Twistwood{6/6} (3) [16/40/3] is not active yet
Centurion Spikesteel{6/6} (0) [10/15/0] takes 12 scorch damage
Turn 8 ends

Turn 9 begins for Orgoth the Hex Fist{6/6} [53 HP]
Orgoth the Hex Fist{6/6} [53 HP] draws Colossal Sundermarr{6/6}
Nether Blackfin{6/6} (2) [11/48/2] reduces its timer
Absorbing Sleetbones{5/5} (3) [10/48/3] reduces its timer
Orgoth the Hex Fist{6/6} [53 HP] plays Jewel Harvester{6/6} (4) [5/28/2]
Orgoth the Hex Fist{6/6} [53 HP] hexes Centurion Spikesteel{6/6} (0) [10/15/0] by 1
Orgoth the Hex Fist{6/6} [53 HP] hexes Hoggernaut MK III{6/6} (1) [10/48/2] by 1
Orgoth the Hex Fist{6/6} [53 HP] hexes Life Vessel{6/6} (2) [15/46/2] by 1
Orgoth the Hex Fist{6/6} [53 HP] hexes Twistwood{6/6} (3) [11/40/3] by 1
Orgoth the Hex Fist{6/6} [53 HP] weakens Centurion Spikesteel{6/6} (0) [7/15/0] by 3
**(Vampirism: +5 Enfeeble: +1) = 6 damage
Cauterizing Fist{5/5} (0) [8/14/0] activates vampirism, draining 6 health from Centurion Spikesteel{6/6} (0) [7/9/0]
Cauterizing Fist{5/5} (0) [8/14/0] inflicts scorch(6) on Centurion Spikesteel{6/6} (0) [7/9/0]
(Attack: +8 Enfeeble: +1) = 9 damage
Cauterizing Fist{5/5} (0) [8/14/0] attacks Centurion Spikesteel{6/6} (0) [7/0/0] for 9 damage and it dies
(Vengance: +9 Ward: -5) = 4 damage
Cauterizing Fist{5/5} (0) [8/10/0] takes 4 vengance damage
(Strike: +3 Enfeeble: +1 Stasis: -6) = 0 damage**
Vali, the Vanquisher{6/6} (1) [9/26/0] bolts Hoggernaut MK III{6/6} (1) [10/48/2] for 0 damage
(Strike: +3 Enfeeble: +1 Stasis: -8) = 0 damage
Vali, the Vanquisher{6/6} (1) [9/26/0] bolts Life Vessel{6/6} (2) [15/46/2] for 0 damage
(Strike: +3 Enfeeble: +1 Stasis: -6) = 0 damage
Vali, the Vanquisher{6/6} (1) [9/26/0] bolts Twistwood{6/6} (3) [11/40/3] for 0 damage
(Frostbreath: +2 Enfeeble: +1 Stasis: -6) = 0 damage
Vali, the Vanquisher{6/6} (1) [9/26/0] breathes frost at Hoggernaut MK III{6/6} (1) [10/48/2] for 0 damage
(Frostbreath: +2 Enfeeble: +1 Stasis: -8) = 0 damage
Vali, the Vanquisher{6/6} (1) [9/26/0] breathes frost at Life Vessel{6/6} (2) [15/46/2] for 0 damage
(Attack: +9 Enfeeble: +1 Shroud: -6) = 4 damage
Vali, the Vanquisher{6/6} (1) [9/26/0] attacks Hoggernaut MK III{6/6} (1) [10/44/2] for 4 damage
(Vampirism: +6 Enfeeble: +1 Stasis: -8) = 0 damage
Nether Blackfin{6/6} (2) [11/48/2] activates vampirism, draining 0 health from Life Vessel{6/6} (2) [15/46/2]
Nether Blackfin{6/6} (2) [11/48/2] is not active yet
(Vampirism: +6 Enfeeble: +1 Stasis: -6) = 0 damage
Absorbing Sleetbones{5/5} (3) [10/48/3] activates vampirism, draining 0 health from Twistwood{6/6} (3) [11/40/3]
Absorbing Sleetbones{5/5} (3) [10/48/3] is not active yet
Jewel Harvester{6/6} (4) [5/28/2] is not active yet
**Cauterizing Fist{5/5} (0) [8/16/0] regenerates 6 health**
Centurion Spikesteel{6/6} (0) [7/0/0] is removed from field
Turn 9 ends

**Comment by TheSench** [comment]
Thanks for the report.  Fixed under https://github.com/TheSench/SIMSpellstone/commit/aa984951c4f080ea1d33f648aab7dfbdc8a9b95a.
