### ISSUE TITLE
Lily and Spear Formation Not Implemented

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#24]

**Comment by TheSench** [comment]
Should be implemented now.  Please give it a test and let me know if you see any issues with it.  It will currently add the following effects to frogs:
1) Pierce equal to their base attack
2) "Bash" skill - deal an extra 25% of their base attack on the first attack of ~the match~ each turn

**Comment by MrClouds** [comment]
Tested it and it appears fixed.

Thanks.
