### ISSUE TITLE
Protect is not properly implemented for case of multiplier and constant amount

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#26]
Elemental Discord is incorrectly implemented.

Underlying issue appears to be that current implementation only allows a constant value or a multiplier, not both.

**Comment by MrClouds** [comment]
The following should be changed:

				var protect_amt = protect;
				if (!protect_amt) {
					var mult = skill.mult;
					if (!target.isActive()) {
						mult += (skill.on_delay_mult || 0);
					}
					protect_amt = Math.ceil(target.health * mult);
				}

Should be changed to: 

				var protect_amt = protect;
				if (skill.mult) {
					var mult = skill.mult;
					if (!target.isActive()) {
						mult += (skill.on_delay_mult || 0);
					}
					protect_amt += Math.ceil(target.health * mult);
				}

**Comment by TheSench** [comment]
Thanks a ton for the bug report!  I tweaked the skull.x + skill.mult logic a bit and added it to the other places that `.mult` was supported.  Let me know if you see any issues with it.

**Comment by MrClouds** [comment]
Looks good to me. Thanks.
