### ISSUE TITLE
Points bug

### ISSUE THREAD

**Issue by qsqa** [TheSench/SIMSpellstone#30]
In simulator_base.js,
```
healthStats.player.percent = stats.taken / stats.total;
healthStats.cpu.percent = stats.taken / stats.total;
```
needs changing to
```
healthStats.player.percent = healthStats.player.taken / healthStats.player.total;
healthStats.cpu.percent = healthStats.cpu.taken / healthStats.cpu.total;
```

This almost works.  However, it can give rise to points scores in excess of 200, suggesting that stats.taken can go negative, i.e. that remaining health can be larger than full health, somehow.  Is invigorate not quite working properly, perhaps?

**Comment by TheSench** [comment]
Thanks for the bug report!  Good catch.
