### ISSUE TITLE
Duplicate BGE names

### ISSUE THREAD

**Issue by qsqa** [TheSench/SIMSpellstone#36]
### The bug

The list of displayed names in the "Battleground Effects" panel contains duplicates: two instances of "Elemental Surge" (ids 107 and 116) and two instances of "The Arena" (ids 514 and 521).

In each case, the skill definitions are different.  For example, in The Arena:

- The Arena (id 514) has slow=1
- The Arena (id 521) has slow=2    <-- this is the one used in the actual Arena

This is confusing.  At a minimum, the names should be different.

### Possible solutions

Please consider making the sim detect the duplicate name and tag the displayed entry with the id, or doing something else to differentiate the namesake effects.  Tool-tips differentiate the two BGEs named "The Arena", but they don't differentiate the two BGEs named "Elemental Surge".

It would also be helpful to sort the BGE names alphabetically.  For one, this would make it easier to search the list; but, perhaps more importantly, it would also make it obvious when a BGE name was a duplicate (and thus that the user should pay close attention to the tool-tip or other differentiating information).

**Comment by TheSench** [comment]
Thanks for the bug report.  I've added some logic to currently take the most recent BGE with a given name and make that the "official one".  The rest are marked as obsolete and will be displayed with a lighter color.  Additionally, I've also added some improvements to the BGE list, making it larger on wider screens and making the current BGEs bold-faced for easier identification.

**Comment by TheSench** [comment]
Additionally, you should see tooltips on a non-mobile browser if you mouse-over the BGEs, which show the descriptions.  The Arena descriptions call out their behavior.  I'm trying to keep from adding special handling for specific BGEs, such as renaming, as I never know when/how the data from Synapse will change.

**Comment by qsqa** [comment]
That's great, thank you!
