### ISSUE TITLE
Amusing bug, period.

### ISSUE THREAD

**Issue by qsqa** [TheSench/SIMSpellstone#38]
You know how it's easy to accidentally include a period at the end of a URL, especially when the URL is quoted in a sentence?  For example: [https://thesench.github.io/SIMSpellstone/DeckBuilder.html?hash=QpLQA.](https://thesench.github.io/SIMSpellstone/DeckBuilder.html?hash=QpLQA.)

When you do that, the sim gets a little overexcited!  Try the link to see what I mean.

**Comment by TheSench** [comment]
Looks like the URL got stripped from your email.  Can you toss me just the
query string (the portion after '?' if you're not familiar with that
terminology)?

**Comment by qsqa** [comment]
hash=QpLQA.

including the period :)

**Comment by TheSench** [comment]
Hah!  I see it.  The deck hashes include the possibility for a multiplier
(any of *_*.' *followed by a second character).  It's been turned off in
the hashing algorithm for a few years now, but it still exists for
backwards compatibility.  It takes the first character, maps it to a
multiple of 64 (0-3), and then takes the second one and maps it to another
value (0-63) and adds it on.  In the case of a missing second character, it
ends up being -1.  Long-story-short, a trailing . gets treated as a
multiplier of 127 by the hash-decoding algorithm.

**Comment by TheSench** [comment]
I'll put in a small fix that will treat a multiplier that is missing its
second character as a multiplier of 1, silently swallowing the trailing
period.

**Comment by qsqa** [comment]
Many thanks.
