### ISSUE TITLE
Fear Aura Not Working

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#41]
Weaken and Hex are not implemented.

**Comment by MrClouds** [comment]
It looks like this is probably related to Synapse changing the hex/weaken to apply after skills. Now in data they read as:

<add_skill id="enfeeblebge" mult=".20" base="health" y="9" delay="0,1,2"/>
<add_skill id="weakenbge" mult=".30" base="health" y="9" delay="3,4"/>

**Comment by TheSench** [comment]
Thanks for the bug report and for that extra info - that made it a lot easier to triage.
