### ISSUE TITLE
Silence not implemented properly

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#49]
There are a few cases where silence is not implemented properly.

Currently in the sim, silence removes corrosive, emberhide, and vengeance. These skills should not be removed by silence.

Regenerate and Reanimate are not removed by silence in the sim. These skills should be removed by silence.

**Comment by TheSench** [comment]
How about Scylla's Fury?  Is that affected?

**Comment by MrClouds** [comment]
> How about Scylla's Fury? Is that affected?

Scylla's Fury is not affected by silence. Scylla still deals damage and gains attack.

**Comment by TheSench** [comment]
How about enraged?  Do units that have been enraged still gain attack?  I'm guessing they do, because it's a status, not a passive skill, although the sim currently stops enraged.
