### ISSUE TITLE
Heal/Regenerate not properly implemented

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#51]
Currently the sim only removes cards at the end of the turns.

This allows cards which have died to be healed back to life. 

Sim should either remove these cards before the end of the turn or not allow them to be healed/regenerated once health drops to 0 or lower.

**Comment by TheSench** [comment]
Can you give an example of this happening?  I think it is a fringe case, as the skills have an "isAlive" check when determining valid targets.  I'll see if I notice anything in the code that is missing one.

**Comment by TheSench** [comment]
I confirmed that regenerate is missing such a check.  Let me know if you saw any others.
