### ISSUE TITLE
More Silence Issues

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#60]
Found a few more issues with silence.

Currently in the sim silence is applied to the hero when direct damage is dealt. The hero cannot be silenced. In run mode it seems possible that the silence is being applied to the hero by Kalyt simply being in the deck. 

Currently in the sim shroud is not removed by silence in the sim. It should be removed.

The current frog BGE lily & spear formation is not removed by silence in the sim. It should also be removed. We are still double checking other BGE effects, but it appears it can remove imbued skills if those skills can normally be silenced.

**Comment by MrClouds** [comment]
It looks like debug mode and regular mode are out of sync regarding Kalyt.

I ran a strong deck with Kalyt against another strong deck with its hero replaced with the most overpowered hero in the game.

In run mode, I win about 85% of the time. I set debug to "first win" though and I rarely if ever win the first match. In fact, several times I made it to 14 matches without a win which should be probabilistically impossible to happen multiple times with me just clicking.

I think the mere presence of Kalyt in a deck is silencing the hero in run mode. Will look at the code to get an idea why.

**Comment by TheSench** [comment]
For shroud, does silence only prevent shroud from blocking skill damage from units that come after the silencer, or does it allow the silencer's direct attack to not be reduced?  I'm assuming it's the first case.

**Comment by TheSench** [comment]
For Lilly & Spear, does it defer the attack boost, or permanently stop it?

**Comment by MrClouds** [comment]
> For shroud, does silence only prevent shroud from blocking skill damage from units that come after the silencer, or does it allow the silencer's direct attack to not be reduced? I'm assuming it's the first case.

Yes, it is the first case. Kalyt's attack will be reduced by the shroud but anything after will not be affected.

**Comment by MrClouds** [comment]
> For Lilly & Spear, does it defer the attack boost, or permanently stop it?

Not sure I understand.

Each turn the frog receives an attack boost/pierce for that turn. Silence will prevent it from receiving this boost, but on turns it is not silenced it will still receive the boost. The attack boost does not stack/behave like berserk if that is the confusion.

**Comment by TheSench** [comment]
Ahh, duh.  Bash is the first attack _each round_.

**Comment by MrClouds** [comment]
> Ahh, duh. Bash is the first attack _each round_.

Right. Looks good to merge now.
