### ISSUE TITLE
Deck Builder hangs with Viracocha

### ISSUE THREAD

**Issue by CodeMagic** [TheSench/SIMSpellstone#62]
The new champion Viracocha doesn't have a faction, but rather than being 'Factionless' it looks like he's straight up missing the <type> attribute in his XML.

This causes a halting error on [line273 of cards_gui.js](https://github.com/TheSench/SIMSpellstone/blob/d243f037984ed44350fa1770e6fecd67bc0ee4b7/scripts/cards_gui.js#L273) when it tries to add the faction name to the class list.

**Comment by eMuonTau** [comment]
@CodeMagic Did you try updating data with "Update Data" button? Embedded card data is 8 days old.

**Comment by TheSench** [comment]
@CodeMagic thanks for the report.  I updated the tool that runs the data updates to now default the `type` field to `0` (factionless) if it's missing in the XML.  After running it, it updated `Viracocha` and it should be working now.
