### ISSUE TITLE
Adaptive Weaponry Not Implemented Properly

### ISSUE THREAD

**Issue by MrClouds** [TheSench/SIMSpellstone#63]
The devs decided to do something different and have the faction BGE effects apply to the new Void Champ even though it does not belong to those factions.

Originally they tried to do achieve this by adding a new "card" XML attribute but this didn't work so they rolled it back, so the sim was accurate.

They were able to fix it now and the buff is active in game. Instead of using a new attribute, they're just applying all the effects to the void mecha type.

<add_skill id="legion" x="5" yy="0,16" delay="2"/>

<add_skill id="barrage" x="6" yy="0,16" delay="2"/>

<add_skill id="venom" x="5" yy="0,16" delay="2"/>

It isn't working in the sim. I'm assuming this is because you aren't handling the void (0) faction.

**Comment by MrClouds** [comment]
My mistake. It appears to be working now. Game files may not have been updated at the time I checked.

**Comment by TheSench** [comment]
Awesome!  Thanks for keeping me updated.
